using System;
using System.Collections.Generic;

public static class SceneTypeMap
{
    private static readonly string[] SceneNames =
    {
        "",
        "TitleScene",
        "Lobby_Over",
        "Lobby_Under",
        "TutorialScene_1",
        "Stage1_1",
        "Stage1_2",
        "Stage1_3",
        "Stage1_4",
        "Stage1_5",
        "Stage1_6",
        "Stage1_7",
        "Stage1_8",
        "Stage1_9",
        "Stage1_10",
        "Stage1_11",
        "Stage2_1",
        "Stage2_2",
        "Stage2_3",
        "Stage2_4",
        "Stage2_5",
        "Stage2_6",
        "Stage2_7",
        "Stage2_8",
        "Stage2_9",
        "Stage2_10",
        "Stage3_1",
        "Stage3_2",
        "Stage3_3",
        "Stage3_4",
        "Stage3_5",
        "Stage3_6",
        "Stage3_7",
        "Stage3_8",
        "Stage3_9",
        "Stage3_10",
        "Stage3_11",
        "Stage3_12",
        "Stage3_13",
        "Stage3_14",
        "Stage3_15",
        "Stage4_1",
        "Stage4_2",
        "Stage4_3",
        "Stage4_4",
        "Stage4_5",
        "Stage4_6",
        "Stage4_7",
        "Stage4_8",
        "Stage4_9",
        "Stage4_10",
        "Stage4_11",
        "EndingScene_1",
        "EndingScene_2",
        "TutorialScene_2",
    };

    private static readonly string[] ScenePaths =
    {
        "",
        "Assets/Scenes/GameScenes/TitleScene.unity",
        "Assets/Scenes/GameScenes/LobbyScenes/Lobby_Over.unity",
        "Assets/Scenes/GameScenes/LobbyScenes/Lobby_Under.unity",
        "Assets/Scenes/GameScenes/TutorialScenes/TutorialScene_1.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_1.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_2.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_3.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_4.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_5.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_6.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_7.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_8.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_9.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_10.unity",
        "Assets/Scenes/GameScenes/Level1/Stage1_11.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_1.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_2.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_3.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_4.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_5.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_6.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_7.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_8.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_9.unity",
        "Assets/Scenes/GameScenes/Level2/Stage2_10.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_1.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_2.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_3.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_4.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_5.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_6.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_7.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_8.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_9.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_10.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_11.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_12.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_13.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_14.unity",
        "Assets/Scenes/GameScenes/Level3/Stage3_15.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_1.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_2.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_3.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_4.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_5.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_6.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_7.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_8.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_9.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_10.unity",
        "Assets/Scenes/GameScenes/Level4/Stage4_11.unity",
        "Assets/Scenes/GameScenes/EndingScene_1.unity",
        "Assets/Scenes/GameScenes/EndingScene_2.unity",
        "Assets/Scenes/GameScenes/TutorialScenes/TutorialScene_2.unity",
    };

    private static readonly bool[] EnabledInBuildSettings =
    {
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
    };

    private static readonly Dictionary<string, SceneType> NameToType = new(StringComparer.Ordinal)
    {
        { "TitleScene", SceneType.TitleScene },
        { "Lobby_Over", SceneType.Lobby_Over },
        { "Lobby_Under", SceneType.Lobby_Under },
        { "TutorialScene_1", SceneType.TutorialScene_1 },
        { "Stage1_1", SceneType.Stage1_1 },
        { "Stage1_2", SceneType.Stage1_2 },
        { "Stage1_3", SceneType.Stage1_3 },
        { "Stage1_4", SceneType.Stage1_4 },
        { "Stage1_5", SceneType.Stage1_5 },
        { "Stage1_6", SceneType.Stage1_6 },
        { "Stage1_7", SceneType.Stage1_7 },
        { "Stage1_8", SceneType.Stage1_8 },
        { "Stage1_9", SceneType.Stage1_9 },
        { "Stage1_10", SceneType.Stage1_10 },
        { "Stage1_11", SceneType.Stage1_11 },
        { "Stage2_1", SceneType.Stage2_1 },
        { "Stage2_2", SceneType.Stage2_2 },
        { "Stage2_3", SceneType.Stage2_3 },
        { "Stage2_4", SceneType.Stage2_4 },
        { "Stage2_5", SceneType.Stage2_5 },
        { "Stage2_6", SceneType.Stage2_6 },
        { "Stage2_7", SceneType.Stage2_7 },
        { "Stage2_8", SceneType.Stage2_8 },
        { "Stage2_9", SceneType.Stage2_9 },
        { "Stage2_10", SceneType.Stage2_10 },
        { "Stage3_1", SceneType.Stage3_1 },
        { "Stage3_2", SceneType.Stage3_2 },
        { "Stage3_3", SceneType.Stage3_3 },
        { "Stage3_4", SceneType.Stage3_4 },
        { "Stage3_5", SceneType.Stage3_5 },
        { "Stage3_6", SceneType.Stage3_6 },
        { "Stage3_7", SceneType.Stage3_7 },
        { "Stage3_8", SceneType.Stage3_8 },
        { "Stage3_9", SceneType.Stage3_9 },
        { "Stage3_10", SceneType.Stage3_10 },
        { "Stage3_11", SceneType.Stage3_11 },
        { "Stage3_12", SceneType.Stage3_12 },
        { "Stage3_13", SceneType.Stage3_13 },
        { "Stage3_14", SceneType.Stage3_14 },
        { "Stage3_15", SceneType.Stage3_15 },
        { "Stage4_1", SceneType.Stage4_1 },
        { "Stage4_2", SceneType.Stage4_2 },
        { "Stage4_3", SceneType.Stage4_3 },
        { "Stage4_4", SceneType.Stage4_4 },
        { "Stage4_5", SceneType.Stage4_5 },
        { "Stage4_6", SceneType.Stage4_6 },
        { "Stage4_7", SceneType.Stage4_7 },
        { "Stage4_8", SceneType.Stage4_8 },
        { "Stage4_9", SceneType.Stage4_9 },
        { "Stage4_10", SceneType.Stage4_10 },
        { "Stage4_11", SceneType.Stage4_11 },
        { "EndingScene_1", SceneType.EndingScene_1 },
        { "EndingScene_2", SceneType.EndingScene_2 },
        { "TutorialScene_2", SceneType.TutorialScene_2 },
    };

    public static int TotalCount => SceneNames.Length;
    public static int BuildSceneCount => SceneNames.Length - 1;
    public static string GetName(SceneType sceneType) => SceneNames[(int)sceneType];
    public static string GetPath(SceneType sceneType) => ScenePaths[(int)sceneType];
    public static bool IsEnabledInBuildSettings(SceneType sceneType) => EnabledInBuildSettings[(int)sceneType];
    public static bool TryGetTypeByName(string sceneName, out SceneType sceneType) => NameToType.TryGetValue(sceneName, out sceneType);
}
